# This is a basic workflow to help you get started with Actions

name: Build_DSM701_Bootloader

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: edit ds918 config
        env:
          DS918P_PID: ${{ secrets.DS918P_PID }}
          DS918P_VID: ${{ secrets.DS918P_VID }}
          DS918P_SN: ${{ secrets.DS918P_SN }}
          DS918P_MAC: ${{ secrets.DS918P_MAC }}
        run: |
          chmod +x rp-helper.sh
          sed -i "s/1234XXX123/${DS918P_SN}/g" apollolake_user_config.json
          sed -i "s/XXYYXXYYXXYY/${DS918P_MAC}/g" apollolake_user_config.json
          sed -i "s/0x46f4/${DS918P_VID}/g" apollolake_user_config.json
          sed -i "s/0x0001/${DS918P_PID}/g" apollolake_user_config.json

      - name: build ds918 7.0.1
        run: |
          ./rp-helper.sh build apollolake-7.0.1-42218
        
      - name: 配置引导镜像
        run: |
          ./rp-helper.sh ext apollolake-7.0.1-42218 add https://github.com/jumkey/redpill-load/raw/develop/redpill-virtio/rpext-index.json
          ./rp-helper.sh ext apollolake-7.0.1-42218 add https://raw.githubusercontent.com/pocopico/rp-ext/master/mpt3sas/rpext-index.json
          ./rp-helper.sh ext apollolake-7.0.1-42218 add https://raw.githubusercontent.com/pocopico/rp-ext/master/e1000/rpext-index.json
          ./rp-helper.sh ext apollolake-7.0.1-42218 add https://raw.githubusercontent.com/pocopico/rp-ext/master/e1000e/rpext-index.json
          ./rp-helper.sh ext apollolake-7.0.1-42218 add https://raw.githubusercontent.com/pocopico/rp-ext/master/i40e/rpext-index.json
          ./rp-helper.sh ext apollolake-7.0.1-42218 add https://raw.githubusercontent.com/pocopico/rp-ext/master/iavf/rpext-index.json
          ./rp-helper.sh ext apollolake-7.0.1-42218 add https://raw.githubusercontent.com/pocopico/rp-ext/master/igb/rpext-index.json
          ./rp-helper.sh ext apollolake-7.0.1-42218 add https://raw.githubusercontent.com/pocopico/rp-ext/master/igbvf/rpext-index.json
          ./rp-helper.sh ext apollolake-7.0.1-42218 add https://raw.githubusercontent.com/pocopico/rp-ext/master/ixgbe/rpext-index.json
          ./rp-helper.sh ext apollolake-7.0.1-42218 add https://raw.githubusercontent.com/pocopico/rp-ext/master/ixgbevf/rpext-index.json
          ./rp-helper.sh ext apollolake-7.0.1-42218 add https://raw.githubusercontent.com/pocopico/rp-ext/master/megaraid_sas/rpext-index.json
          ./rp-helper.sh ext apollolake-7.0.1-42218 add https://raw.githubusercontent.com/pocopico/rp-ext/master/mpt3sas/rpext-index.json
          ./rp-helper.sh ext apollolake-7.0.1-42218 add https://raw.githubusercontent.com/pocopico/rp-ext/master/qlcnic/rpext-index.json
          ./rp-helper.sh ext apollolake-7.0.1-42218 add https://raw.githubusercontent.com/pocopico/rp-ext/master/qla2xxx/rpext-index.json
          ./rp-helper.sh ext apollolake-7.0.1-42218 add https://raw.githubusercontent.com/pocopico/rp-ext/master/r8101/rpext-index.json
          ./rp-helper.sh ext apollolake-7.0.1-42218 add https://raw.githubusercontent.com/pocopico/rp-ext/master/r8125/rpext-index.json
          ./rp-helper.sh ext apollolake-7.0.1-42218 add https://raw.githubusercontent.com/pocopico/rp-ext/master/r8168/rpext-index.json
          ./rp-helper.sh ext apollolake-7.0.1-42218 add https://raw.githubusercontent.com/pocopico/rp-ext/master/r8169/rpext-index.json
          ./rp-helper.sh ext apollolake-7.0.1-42218 add https://raw.githubusercontent.com/pocopico/rp-ext/master/redpill/rpext-index.json
          ./rp-helper.sh ext apollolake-7.0.1-42218 add https://github.com/jumkey/redpill-load/raw/develop/redpill-acpid/rpext-index.json
          ./rp-helper.sh ext apollolake-7.0.1-42218 add https://github.com/pocopico/rp-ext/raw/main/redpill-boot-wait/rpext-index.json
          ./rp-helper.sh ext apollolake-7.0.1-42218 add https://raw.githubusercontent.com/pocopico/rp-ext/master/rtl8150/rpext-index.json
        #  ./rp-helper.sh ext apollolake-7.0.1-42218 add https://raw.githubusercontent.com/pocopico/rp-ext/master/bnx2x/rpext-index.json

      - name: create ds918 7.0.1 image
        run: |
          ./rp-helper.sh auto apollolake-7.0.1-42218

      - name: edit ds3615xs config
        env:
          DS3615_PID: ${{ secrets.DS3615_PID }}
          DS3615_VID: ${{ secrets.DS3615_VID }}
          DS3615_SN: ${{ secrets.DS3615_SN}}
          DS3615_MAC: ${{ secrets.DS3615_MAC}}
        run: |
          sed -i "s/1234XXX123/${DS3615_SN}/g" bromolow_user_config.json
          sed -i "s/XXYYXXYYXXYY/${DS3615_MAC}/g" bromolow_user_config.json
          sed -i "s/0x46f4/${DS3615_VID}/g" bromolow_user_config.json
          sed -i "s/0x0001/${DS3615_PID}/g" bromolow_user_config.json

      - name: build ds3615xs 7.0.1
        run: |
          ./rp-helper.sh build bromolow-7.0.1-42218
        
      - name: 配置引导镜像
        run: |
          ./rp-helper.sh ext bromolow-7.0.1-42218 add https://github.com/jumkey/redpill-load/raw/develop/redpill-virtio/rpext-index.json
          ./rp-helper.sh ext bromolow-7.0.1-42218 add https://raw.githubusercontent.com/pocopico/rp-ext/master/mpt3sas/rpext-index.json
          ./rp-helper.sh ext bromolow-7.0.1-42218 add https://raw.githubusercontent.com/pocopico/rp-ext/master/e1000/rpext-index.json
          ./rp-helper.sh ext bromolow-7.0.1-42218 add https://raw.githubusercontent.com/pocopico/rp-ext/master/e1000e/rpext-index.json
          ./rp-helper.sh ext bromolow-7.0.1-42218 add https://raw.githubusercontent.com/pocopico/rp-ext/master/i40e/rpext-index.json
          ./rp-helper.sh ext bromolow-7.0.1-42218 add https://raw.githubusercontent.com/pocopico/rp-ext/master/iavf/rpext-index.json
          ./rp-helper.sh ext bromolow-7.0.1-42218 add https://raw.githubusercontent.com/pocopico/rp-ext/master/igb/rpext-index.json
          ./rp-helper.sh ext bromolow-7.0.1-42218 add https://raw.githubusercontent.com/pocopico/rp-ext/master/igbvf/rpext-index.json
          ./rp-helper.sh ext bromolow-7.0.1-42218 add https://raw.githubusercontent.com/pocopico/rp-ext/master/ixgbe/rpext-index.json
          ./rp-helper.sh ext bromolow-7.0.1-42218 add https://raw.githubusercontent.com/pocopico/rp-ext/master/ixgbevf/rpext-index.json
          ./rp-helper.sh ext bromolow-7.0.1-42218 add https://raw.githubusercontent.com/pocopico/rp-ext/master/megaraid_sas/rpext-index.json
          ./rp-helper.sh ext bromolow-7.0.1-42218 add https://raw.githubusercontent.com/pocopico/rp-ext/master/mpt3sas/rpext-index.json
          ./rp-helper.sh ext bromolow-7.0.1-42218 add https://raw.githubusercontent.com/pocopico/rp-ext/master/qlcnic/rpext-index.json
          ./rp-helper.sh ext bromolow-7.0.1-42218 add https://raw.githubusercontent.com/pocopico/rp-ext/master/qla2xxx/rpext-index.json
          ./rp-helper.sh ext bromolow-7.0.1-42218 add https://raw.githubusercontent.com/pocopico/rp-ext/master/r8101/rpext-index.json
          ./rp-helper.sh ext bromolow-7.0.1-42218 add https://raw.githubusercontent.com/pocopico/rp-ext/master/r8125/rpext-index.json
          ./rp-helper.sh ext bromolow-7.0.1-42218 add https://raw.githubusercontent.com/pocopico/rp-ext/master/r8168/rpext-index.json
          ./rp-helper.sh ext bromolow-7.0.1-42218 add https://raw.githubusercontent.com/pocopico/rp-ext/master/r8169/rpext-index.json
          ./rp-helper.sh ext bromolow-7.0.1-42218 add https://raw.githubusercontent.com/pocopico/rp-ext/master/redpill/rpext-index.json
          ./rp-helper.sh ext bromolow-7.0.1-42218 add https://github.com/jumkey/redpill-load/raw/develop/redpill-acpid/rpext-index.json
          ./rp-helper.sh ext bromolow-7.0.1-42218 add https://github.com/pocopico/rp-ext/raw/main/redpill-boot-wait/rpext-index.json
          ./rp-helper.sh ext bromolow-7.0.1-42218 add https://raw.githubusercontent.com/pocopico/rp-ext/master/rtl8150/rpext-index.json
          ./rp-helper.sh ext bromolow-7.0.1-42218 add https://raw.githubusercontent.com/pocopico/rp-ext/master/bnx2x/rpext-index.json

          
      - name: create ds3615xs 7.0.1 image
        run: |
          ./rp-helper.sh auto bromolow-7.0.1-42218

      - name: upload images to Wetrans
        env: 
          WXPUSH_TOKEN: ${{ secrets.WXPUSH_TOKEN}}
          WXPUSER_UID: ${{ secrets.WXPUSER_UID }}
          PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
        run: |
          sudo mkdir firmware
          sudo mv -f images/*.img firmware/
          curl -sL https://git.io/file-transfer | sh 
          wetrans=$(./transfer wet -s -p 16 --no-progress firmware/)
          wetrans=$(echo $wetrans | grep -o -E "https[^ ]*")
          sudo curl -G "http://wxpusher.zjiecode.com/api/send/message/?appToken=${WXPUSH_TOKEN}&uid=${WXPUSER_UID}" \
            --data-urlencode "content=$wetrans" > /dev/null
          sudo curl -G "http://www.pushplus.plus/send" \
            -H "Content-Type=application/json" \
            --data-urlencode "token=${PUSHPLUS_TOKEN}" \
            --data-urlencode "title=image file download url" \
            --data-urlencode "content=$wetrans" > /dev/null
          
